name: Code Generation

on:
  push:
    branches: ["main"]

  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: frenck/action-setup-yq@v1
      - name: Downgrade OAS
        run: bash scripts/downgrade-oas-version.sh
  build:
    needs: [ setup ]
    runs-on: ubuntu-latest
    strategy:
            matrix:
                target:
                    - go-gin-server
                    - python-flask 
                cx-version:
                    # downgradePath represents the spec file path as created as 
                    # part of scripts/downgrade-oas-version.sh in a previous job 
                    - {semantic: "5.0", downgradePath: "5dot0"}
                    - {semantic: "4.6", downgradePath: "4dot6"}

    steps:
      - run: echo "Generate Code"
      - name: Generate Server ${{ specPath }} 
        uses: openapi-generators/openapitools-generator-action@v1
        with:
          generator: ${{ matrix.target }}
          openapi-file: ./.backward-compatible-versions/corex-${{matrix.cx-version.downgradePath}}-304.yaml
          command-args: -o generated/${{ matrix.cx-version.semantic }}/${{ matrix.target }}
  pr:
    needs: [ build ]
    runs-on: ubuntu-latest 
    steps:
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: \[AUTOMATED\] Update generated sample server implementations
          title: \[AUTOMATED\] Update generated sample server implementations 